### PR TITLE
Import/Export Testing

### PR DESCRIPTION
**Pull request by silvanheller**
This PR contains simple testing functionality for import/export code. The goal is to narrow a bug when importing JSON exports. 

Since those tests test the CLI, i added a fourth subproject `cottontaildb-test` which contains test-utils. This is the preferred way to share testing code among modules in Kotlin/Gradle.

@ppanopticon could you have a look at why the `ExportImportCommandTest.exportImport` test is failing? I am unable to truncate an entity using the exact same code as in the CLI. This means i am unable to test the import functionality currently.

### CODE REVIEW

**Comment by ppanopticon** [comment]
I have fixed several issues on master. Can you please try to merge and run your tests again?

I'm not quite sure what you mean by 

> I am unable to truncate an entity using the exact same code as in the CLI. This means i am unable to test the import functionality currently.

I just added the CLI functionality to truncate an entity, i.e., I'm not quite sure what "code" you're referring to. However, in my tests, truncating and entity worked fine.

**Comment by silvanheller** [comment]
Thanks for the fixes! 
I was using the `Clear` command, since the description sounded like it would truncate the entity. In that case, it's unclear to me what the difference between clear and truncate is.

The tests now successfully run, but the performance is not good at all, which is why i've opened #99

**Comment by ppanopticon** [comment]
> Thanks for the fixes! I was using the `Clear` command, since the description sounded like it would truncate the entity. In that case, it's unclear to me what the difference between clear and truncate is.
> 
> The tests now successfully run, but the performance is not good at all, which is why i've opened #99

Good point: `entity clear` should indeed have the same effect but stems from a time where there was no TRUNCATE primitive. I'll remove the command but if it doesn't work, there must still be some bug.

**Review by ppanopticon — CHANGES_REQUESTED** [review]
I have one structural request: I don't like the idea of a _cottontaildb-test_ module and I would argue that unit tests should go into the module that is being tested. 

Consequently, would it make sense to move the common classes (`TestConstants.kt` and `GrpcTestUtils.kt`) to cottontaildb-core, which is required by all the other modules anyway?

**Comment by silvanheller** [comment]
@ppanopticon - as an update: you can find a discussion on the issue [here](https://stackoverflow.com/questions/5644011/multi-project-test-dependencies-with-gradle/60138176#60138176), with the accepted answer relying on a java plugin which does not work well when i tested it, and the answer after that suggesting the solution of this PR

**Comment by ppanopticon** [comment]
> @ppanopticon - as an update: you can find a discussion on the issue [here](https://stackoverflow.com/questions/5644011/multi-project-test-dependencies-with-gradle/60138176#60138176), with the accepted answer relying on a java plugin which does not work well when i tested it, and the answer after that suggesting the solution of this PR

I resolved the issue with the dedicated `cottontaildb-test` module and replaced it by the approach described under the link you posted. Please review. If you're happy with it and if all tests succeed we can merge this.

Sorry for the delay... ^^

**Comment by silvanheller** [comment]
This works for me, thanks! If you want to, you can also make this target `dev` and then have it as part of 0.15

**Comment by ppanopticon** [comment]
> This works for me, thanks! If you want to, you can also make this target `dev` and then have it as part of 0.15

I will do that and resolve the remaining issues.

**Review by ppanopticon — APPROVED** [review]

**Pull request merged**
